CREATE TABLE [CMS_ACL] (
		[ACLID]                [int] IDENTITY(1, 1) NOT NULL,
		[ACLInheritedACLs]     [nvarchar](450) NOT NULL,
		[ACLOwnerNodeID]       [int] NOT NULL,
		[ACLGUID]              [uniqueidentifier] NOT NULL,
		[ACLLastModified]      [datetime] NOT NULL,
		[ACLSiteID]            [int] NULL
) 
ALTER TABLE [CMS_ACL]
	ADD
	CONSTRAINT [PK_CMS_ACL]
	PRIMARY KEY
	CLUSTERED
	([ACLID])
	
	
ALTER TABLE [CMS_ACL]
	ADD
	CONSTRAINT [DEFAULT_CMS_ACL_ACLGUID]
	DEFAULT ('00000000-0000-0000-0000-000000000000') FOR [ACLGUID]
ALTER TABLE [CMS_ACL]
	ADD
	CONSTRAINT [DEFAULT_CMS_ACL_ACLLastModified]
	DEFAULT ('10/30/2008 9:17:31 AM') FOR [ACLLastModified]
ALTER TABLE [CMS_ACL]
	ADD
	CONSTRAINT [DF__CMS_ACL__ACLInhe__060DEAE8]
	DEFAULT ('') FOR [ACLInheritedACLs]
CREATE NONCLUSTERED INDEX [IX_CMS_ACL_ACLInheritedACLs]
	ON [CMS_ACL] ([ACLInheritedACLs])
	
	
CREATE NONCLUSTERED INDEX [IX_CMS_ACL_ACLOwnerNodeID]
	ON [CMS_ACL] ([ACLOwnerNodeID])
	
	
ALTER TABLE [CMS_ACL]
	WITH CHECK
	ADD CONSTRAINT [FK_CMS_ACL_ACLSiteID_CMS_Site]
	FOREIGN KEY ([ACLSiteID]) REFERENCES [CMS_Site] ([SiteID])
ALTER TABLE [CMS_ACL]
	CHECK CONSTRAINT [FK_CMS_ACL_ACLSiteID_CMS_Site]
