CREATE TABLE [COM_SKUTaxClasses] (
		[SKUID]          [int] NOT NULL,
		[TaxClassID]     [int] NOT NULL
) 
ALTER TABLE [COM_SKUTaxClasses]
	ADD
	CONSTRAINT [PK_COM_SKUTaxClasses]
	PRIMARY KEY
	CLUSTERED
	([SKUID], [TaxClassID])
	
	
ALTER TABLE [COM_SKUTaxClasses]
	WITH CHECK
	ADD CONSTRAINT [FK_COM_SKUTaxClasses_SKUID_COM_SKU]
	FOREIGN KEY ([SKUID]) REFERENCES [COM_SKU] ([SKUID])
ALTER TABLE [COM_SKUTaxClasses]
	CHECK CONSTRAINT [FK_COM_SKUTaxClasses_SKUID_COM_SKU]
ALTER TABLE [COM_SKUTaxClasses]
	WITH CHECK
	ADD CONSTRAINT [FK_COM_SKUTaxClasses_TaxClassID_COM_TaxClass]
	FOREIGN KEY ([TaxClassID]) REFERENCES [COM_TaxClass] ([TaxClassID])
ALTER TABLE [COM_SKUTaxClasses]
	CHECK CONSTRAINT [FK_COM_SKUTaxClasses_TaxClassID_COM_TaxClass]
