CREATE TABLE [COM_Wishlist] (
		[UserID]     [int] NOT NULL,
		[SKUID]      [int] NOT NULL,
		[SiteID]     [int] NOT NULL
) 
ALTER TABLE [COM_Wishlist]
	ADD
	CONSTRAINT [PK_COM_Wishlist]
	PRIMARY KEY
	CLUSTERED
	([UserID], [SKUID], [SiteID])
	
	
ALTER TABLE [COM_Wishlist]
	WITH CHECK
	ADD CONSTRAINT [FK_COM_Wishlist_SiteID_CMS_Site]
	FOREIGN KEY ([SiteID]) REFERENCES [CMS_Site] ([SiteID])
ALTER TABLE [COM_Wishlist]
	CHECK CONSTRAINT [FK_COM_Wishlist_SiteID_CMS_Site]
ALTER TABLE [COM_Wishlist]
	WITH CHECK
	ADD CONSTRAINT [FK_COM_Wishlist_SKUID_COM_SKU]
	FOREIGN KEY ([SKUID]) REFERENCES [COM_SKU] ([SKUID])
ALTER TABLE [COM_Wishlist]
	CHECK CONSTRAINT [FK_COM_Wishlist_SKUID_COM_SKU]
ALTER TABLE [COM_Wishlist]
	WITH CHECK
	ADD CONSTRAINT [FK_COM_Wishlist_UserID_CMS_User]
	FOREIGN KEY ([UserID]) REFERENCES [CMS_User] ([UserID])
ALTER TABLE [COM_Wishlist]
	CHECK CONSTRAINT [FK_COM_Wishlist_UserID_CMS_User]
